# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('addrId', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u5730\u5740ID')),
                ('areaId', models.IntegerField(verbose_name='\u56ed\u533aID')),
                ('detailAddress', models.CharField(max_length=30, verbose_name='\u5efa\u7b51\u7269')),
                ('phoneNumber', models.CharField(max_length=30, verbose_name='\u624b\u673a\u53f7\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('areaId', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u56ed\u533aID')),
                ('areaName', models.CharField(max_length=20, verbose_name='\u56ed\u533a\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='busniess',
            fields=[
                ('busniessId', models.AutoField(primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u5546\u5bb6\u540d')),
                ('busniessName', models.CharField(max_length=20, unique=True, verbose_name='\u5546\u5bb6\u767b\u5f55\u540d')),
                ('password', models.CharField(max_length=20, verbose_name='\u5bc6\u7801')),
                ('avatarUrl', models.ImageField(max_length=50, null=True, upload_to='first/busniessImage', verbose_name='\u5546\u5bb6\u5934\u50cf')),
                ('isopen', models.IntegerField(choices=[(0, '\u8425\u4e1a\u4e2d'), (1, '\u505c\u4e1a\u4e2d')], default=0)),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.address')),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('carId', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u5c0f\u8f66ID')),
                ('capability', models.IntegerField(verbose_name='\u5c0f\u8f66\u603b\u5bb9\u91cf')),
                ('usedCapability', models.IntegerField(default=0, verbose_name='\u5df2\u7528\u5bb9\u91cf')),
                ('status', models.IntegerField(choices=[(0, '\u505c\u7528'), (1, '\u4f7f\u7528\u4e2d')], default=0, verbose_name='\u5c0f\u8f66\u72b6\u6001')),
                ('currentPosition', models.CharField(max_length=30, null=True, verbose_name='\u5c0f\u8f66\u4f4d\u7f6e')),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.area', verbose_name='\u56ed\u533aID')),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('goodsId', models.AutoField(primary_key=True, serialize=False, verbose_name='\u4e3b\u952e')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('quantity', models.IntegerField(verbose_name='\u5546\u54c1\u6570\u91cf')),
                ('picUrl', models.ImageField(max_length=50, null=True, upload_to='first/goodsImag', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('sales_volume', models.IntegerField(verbose_name='\u9500\u552e\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderId', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='\u8ba2\u5355ID')),
                ('payMoney', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u652f\u4ed8\u91d1\u989d')),
                ('ordersTime', models.TimeField(auto_now_add=True, verbose_name='\u8ba2\u5355\u521b\u5efa\u65f6\u95f4')),
                ('completeTime', models.TimeField(auto_now_add=True, null=True, verbose_name='\u8ba2\u5355\u5b8c\u6210\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(0, '\u5df2\u63d0\u4ea4'), (1, '\u5df2\u63a5\u53d7'), (2, '\u5df2\u5b8c\u6210')], default=0, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('busniessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.busniess', verbose_name='\u5546\u5bb6ID')),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.car', verbose_name='\u5c0f\u8f66ID')),
            ],
        ),
        migrations.CreateModel(
            name='order_goods',
            fields=[
                ('serialNUmber', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5e8f\u5217\u53f7')),
                ('goodsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.goods')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.order')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7528\u6237\u540d(\u7535\u8bdd)')),
                ('password', models.CharField(max_length=20, verbose_name='\u5bc6\u7801')),
                ('avatarUrl', models.ImageField(max_length=50, null=True, upload_to='first/Userimage/', verbose_name='\u7528\u6237\u5934\u50cf')),
                ('nickName', models.CharField(max_length=30, null=True, verbose_name='\u7528\u6237\u6635\u79f0')),
                ('addressId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first.address', verbose_name='\u5730\u5740id')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.User', verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='order',
            name='useraddr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.address', verbose_name='\u7528\u6237\u6536\u8d27\u5730\u5740'),
        ),
    ]
